import {
  Van,
  Rep,
  RelayRep,
  SyncLog,
  QueueItem,
  APIEndpoint,
  SystemHealth,
  RecentActivity,
  SyncMetrics,
  DashboardKPIs,
  Route,
} from "./types"

export const dummyVans: Van[] = [
  {
    id: "1",
    vanCode: "VAN-001",
    registrationNumber: "ABC-1234",
    branch: "Riyadh",
    mainRepId: "1",
    mainRepName: "Ahmed Ali",
    relayRepIds: ["7", "8"],
    relayRepNames: ["Saeed Mansour", "Tariq Fahad"],
    capacity: 5000, // kg
    status: "active",
    lastSync: new Date(Date.now() - 2 * 60 * 60 * 1000),
    routeId: "r1",
    routeName: "Route A - Central Riyadh",
    inventoryLoaded: true,
    currentLoad: 4200,
  },
  {
    id: "2",
    vanCode: "VAN-002",
    registrationNumber: "DEF-5678",
    branch: "Jeddah",
    mainRepId: "2",
    mainRepName: "Mohammed Hassan",
    relayRepIds: ["9"],
    relayRepNames: ["Hamad Zaid"],
    capacity: 5000,
    status: "active",
    lastSync: new Date(Date.now() - 1 * 60 * 60 * 1000),
    routeId: "r2",
    routeName: "Route B - North Jeddah",
    inventoryLoaded: true,
    currentLoad: 3800,
  },
  {
    id: "3",
    vanCode: "VAN-003",
    registrationNumber: "GHI-9012",
    branch: "Dammam",
    mainRepId: "3",
    mainRepName: "Khalid Ibrahim",
    relayRepIds: ["10"],
    relayRepNames: ["Fahad Nasser"],
    capacity: 5000,
    status: "active",
    lastSync: new Date(Date.now() - 30 * 60 * 1000),
    routeId: "r3",
    routeName: "Route C - East Dammam",
    inventoryLoaded: true,
    currentLoad: 4500,
  },
  {
    id: "4",
    vanCode: "VAN-004",
    registrationNumber: "JKL-3456",
    branch: "Riyadh",
    mainRepId: "4",
    mainRepName: "Omar Abdullah",
    relayRepIds: ["7"],
    relayRepNames: ["Saeed Mansour"],
    capacity: 5000,
    status: "maintenance",
    lastSync: new Date(Date.now() - 24 * 60 * 60 * 1000),
    routeId: "r4",
    routeName: "Route D - South Riyadh",
    inventoryLoaded: false,
    currentLoad: 0,
  },
  {
    id: "5",
    vanCode: "VAN-005",
    registrationNumber: "MNO-7890",
    branch: "Jeddah",
    mainRepId: "5",
    mainRepName: "Yusuf Saleh",
    relayRepIds: [],
    relayRepNames: [],
    capacity: 5000,
    status: "active",
    lastSync: new Date(Date.now() - 45 * 60 * 1000),
    routeId: "r5",
    routeName: "Route E - West Jeddah",
    inventoryLoaded: true,
    currentLoad: 3200,
  },
  {
    id: "6",
    vanCode: "VAN-006",
    registrationNumber: "PQR-2468",
    branch: "Dammam",
    mainRepId: undefined,
    mainRepName: undefined,
    relayRepIds: [],
    relayRepNames: [],
    capacity: 5000,
    status: "inactive",
    lastSync: undefined,
    inventoryLoaded: false,
    currentLoad: 0,
  },
]

export const dummyReps: Rep[] = [
  {
    id: "1",
    name: "Ahmed Ali",
    phone: "+966501234567",
    email: "ahmed.ali@example.com",
    role: "main",
    assignedVanId: "1",
    assignedVanCode: "VAN-001",
    shiftTiming: "full-day",
    branch: "Riyadh",
    status: "active",
    performance: {
      totalSales: 125000,
      syncSuccessRate: 98.5,
      lastSyncDate: new Date(Date.now() - 2 * 60 * 60 * 1000),
    },
  },
  {
    id: "2",
    name: "Mohammed Hassan",
    phone: "+966502345678",
    email: "mohammed.hassan@example.com",
    role: "main",
    assignedVanId: "2",
    assignedVanCode: "VAN-002",
    shiftTiming: "full-day",
    branch: "Jeddah",
    status: "active",
    performance: {
      totalSales: 142000,
      syncSuccessRate: 97.2,
      lastSyncDate: new Date(Date.now() - 1 * 60 * 60 * 1000),
    },
  },
  {
    id: "3",
    name: "Khalid Ibrahim",
    phone: "+966503456789",
    email: "khalid.ibrahim@example.com",
    role: "main",
    assignedVanId: "3",
    assignedVanCode: "VAN-003",
    shiftTiming: "full-day",
    branch: "Dammam",
    status: "active",
    performance: {
      totalSales: 118000,
      syncSuccessRate: 95.8,
      lastSyncDate: new Date(Date.now() - 30 * 60 * 1000),
    },
  },
  {
    id: "4",
    name: "Omar Abdullah",
    phone: "+966504567890",
    email: "omar.abdullah@example.com",
    role: "main",
    assignedVanId: "4",
    assignedVanCode: "VAN-004",
    shiftTiming: "full-day",
    branch: "Riyadh",
    status: "on-leave",
    performance: {
      totalSales: 98000,
      syncSuccessRate: 96.5,
      lastSyncDate: new Date(Date.now() - 24 * 60 * 60 * 1000),
    },
  },
  {
    id: "5",
    name: "Yusuf Saleh",
    phone: "+966505678901",
    email: "yusuf.saleh@example.com",
    role: "main",
    assignedVanId: "5",
    assignedVanCode: "VAN-005",
    shiftTiming: "full-day",
    branch: "Jeddah",
    status: "active",
    performance: {
      totalSales: 135000,
      syncSuccessRate: 99.1,
      lastSyncDate: new Date(Date.now() - 45 * 60 * 1000),
    },
  },
]

export const dummyRelayReps: RelayRep[] = [
  {
    id: "7",
    name: "Saeed Mansour",
    phone: "+966507890123",
    email: "saeed.mansour@example.com",
    assignedVanIds: ["1", "4"],
    assignedVanCodes: ["VAN-001", "VAN-004"],
    assignedVanName: "VAN-001",
    type: "backup",
    shift: "Evening",
    shiftTiming: "evening",
    branch: "Riyadh",
    status: "active",
    replacementHistory: [
      {
        date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        vanCode: "VAN-001",
        replacedRepId: "1",
        replacedRepName: "Ahmed Ali",
        reason: "Emergency leave",
      },
      {
        date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        vanCode: "VAN-004",
        replacedRepId: "4",
        replacedRepName: "Omar Abdullah",
        reason: "Scheduled leave",
      },
    ],
  },
  {
    id: "8",
    name: "Tariq Fahad",
    phone: "+966508901234",
    email: "tariq.fahad@example.com",
    assignedVanIds: ["1"],
    assignedVanCodes: ["VAN-001"],
    assignedVanName: "VAN-001",
    type: "replacement",
    shift: "Night",
    shiftTiming: "night",
    branch: "Riyadh",
    status: "active",
    replacementHistory: [
      {
        date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
        vanCode: "VAN-001",
        replacedRepId: "1",
        replacedRepName: "Ahmed Ali",
        reason: "Shift rotation",
      },
    ],
  },
  {
    id: "9",
    name: "Hamad Zaid",
    phone: "+966509012345",
    email: "hamad.zaid@example.com",
    assignedVanIds: ["2"],
    assignedVanCodes: ["VAN-002"],
    assignedVanName: "VAN-002",
    type: "backup",
    shift: "Morning",
    shiftTiming: "morning",
    branch: "Jeddah",
    status: "active",
    replacementHistory: [],
  },
  {
    id: "10",
    name: "Fahad Nasser",
    phone: "+966506789012",
    email: "fahad.nasser@example.com",
    assignedVanIds: ["3"],
    assignedVanCodes: ["VAN-003"],
    assignedVanName: "VAN-003",
    type: "replacement",
    shift: "Evening",
    shiftTiming: "evening",
    branch: "Dammam",
    status: "active",
    replacementHistory: [
      {
        date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
        vanCode: "VAN-003",
        replacedRepId: "3",
        replacedRepName: "Khalid Ibrahim",
        reason: "Medical leave",
      },
    ],
  },
]

export const dummyRoutes: Route[] = [
  {
    id: "r1",
    name: "Route A - Central Riyadh",
    vanId: "1",
    shopCount: 15,
    shops: Array.from({ length: 15 }, (_, i) => ({
      id: `shop-${i + 1}`,
      name: `Shop ${i + 1}`,
      address: `Central Riyadh, Street ${i + 1}`,
      contact: `+9665${1000000 + i}`,
    })),
  },
  {
    id: "r2",
    name: "Route B - North Jeddah",
    vanId: "2",
    shopCount: 12,
    shops: Array.from({ length: 12 }, (_, i) => ({
      id: `shop-${i + 16}`,
      name: `Shop ${i + 16}`,
      address: `North Jeddah, Avenue ${i + 1}`,
      contact: `+9665${2000000 + i}`,
    })),
  },
  {
    id: "r3",
    name: "Route C - East Dammam",
    vanId: "3",
    shopCount: 18,
    shops: Array.from({ length: 18 }, (_, i) => ({
      id: `shop-${i + 28}`,
      name: `Shop ${i + 28}`,
      address: `East Dammam, Road ${i + 1}`,
      contact: `+9665${3000000 + i}`,
    })),
  },
]

export const dummySyncLogs: SyncLog[] = [
  {
    id: "1",
    repId: "1",
    repName: "Ahmed Ali",
    vanId: "1",
    vanCode: "VAN-001",
    type: "sales",
    status: "success",
    duration: 1250,
    timestamp: new Date(Date.now() - 10 * 60 * 1000),
    retryCount: 0,
  },
  {
    id: "2",
    repId: "2",
    repName: "Mohammed Hassan",
    vanId: "2",
    vanCode: "VAN-002",
    type: "inventory",
    status: "success",
    duration: 980,
    timestamp: new Date(Date.now() - 25 * 60 * 1000),
    retryCount: 0,
  },
  {
    id: "3",
    repId: "3",
    repName: "Khalid Ibrahim",
    vanId: "3",
    vanCode: "VAN-003",
    type: "sales",
    status: "failed",
    duration: 2500,
    timestamp: new Date(Date.now() - 45 * 60 * 1000),
    errorMessage: "Connection timeout - Network unavailable",
    retryCount: 2,
  },
  {
    id: "4",
    repId: "1",
    repName: "Ahmed Ali",
    vanId: "1",
    vanCode: "VAN-001",
    type: "payment",
    status: "success",
    duration: 1100,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    retryCount: 0,
  },
  {
    id: "5",
    repId: "5",
    repName: "Yusuf Saleh",
    vanId: "5",
    vanCode: "VAN-005",
    type: "return",
    status: "failed",
    duration: 3200,
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    errorMessage: "Invalid payload format - Missing required fields",
    retryCount: 1,
  },
]

export const dummyQueueItems: QueueItem[] = [
  {
    id: "1",
    type: "sales_sync",
    vanId: "1",
    vanCode: "VAN-001",
    repId: "1",
    repName: "Ahmed Ali",
    payloadSize: 2048,
    status: "processing",
    createdAt: new Date(Date.now() - 5 * 60 * 1000),
    retryCount: 0,
    priority: "high",
  },
  {
    id: "2",
    type: "inventory_sync",
    vanId: "2",
    vanCode: "VAN-002",
    repId: "2",
    repName: "Mohammed Hassan",
    payloadSize: 4096,
    status: "pending",
    createdAt: new Date(Date.now() - 10 * 60 * 1000),
    retryCount: 0,
    priority: "medium",
  },
  {
    id: "3",
    type: "payment_sync",
    vanId: "3",
    vanCode: "VAN-003",
    repId: "3",
    repName: "Khalid Ibrahim",
    payloadSize: 1024,
    status: "pending",
    createdAt: new Date(Date.now() - 15 * 60 * 1000),
    retryCount: 0,
    priority: "high",
  },
  {
    id: "4",
    type: "sales_sync",
    vanId: "5",
    vanCode: "VAN-005",
    repId: "5",
    repName: "Yusuf Saleh",
    payloadSize: 3072,
    status: "failed",
    createdAt: new Date(Date.now() - 20 * 60 * 1000),
    retryCount: 3,
    priority: "high",
  },
]

export const dummyAPIEndpoints: APIEndpoint[] = [
  {
    id: "1",
    name: "Get Van List",
    method: "GET",
    url: "/api/v1/vans",
    description: "Retrieve list of all vans with their details",
    status: "active",
    category: "van",
  },
  {
    id: "2",
    name: "Get Rep List",
    method: "GET",
    url: "/api/v1/reps",
    description: "Retrieve list of all sales representatives",
    status: "active",
    category: "rep",
  },
  {
    id: "3",
    name: "Sync Sales",
    method: "POST",
    url: "/api/v1/sync/sales",
    description: "Sync sales data from Van Sales App to Odoo ERP",
    status: "active",
    category: "sales",
  },
  {
    id: "4",
    name: "Sync Inventory",
    method: "POST",
    url: "/api/v1/sync/inventory",
    description: "Sync inventory loads and stock levels",
    status: "active",
    category: "inventory",
  },
  {
    id: "5",
    name: "Sync Payments",
    method: "POST",
    url: "/api/v1/sync/payments",
    description: "Sync payment transactions",
    status: "active",
    category: "sales",
  },
  {
    id: "6",
    name: "Sync Returns",
    method: "POST",
    url: "/api/v1/sync/returns",
    description: "Sync return transactions",
    status: "active",
    category: "sales",
  },
  {
    id: "7",
    name: "Get Van Status",
    method: "GET",
    url: "/api/v1/vans/{id}/status",
    description: "Get current status of a specific van",
    status: "active",
    category: "van",
  },
  {
    id: "8",
    name: "Get Route Details",
    method: "GET",
    url: "/api/v1/routes/{id}",
    description: "Get route details with shop list",
    status: "active",
    category: "van",
  },
]

export const dummySystemHealth: SystemHealth[] = [
  {
    serverUptime: 7200000,
    jobWorkersActive: 4,
    queueSize: 12,
    cpuUsage: 45.2,
    memoryUsage: 62.8,
    apiLatency: 125,
    timestamp: new Date(Date.now() - 60 * 60 * 1000),
  },
  {
    serverUptime: 7260000,
    jobWorkersActive: 4,
    queueSize: 10,
    cpuUsage: 48.5,
    memoryUsage: 64.1,
    apiLatency: 132,
    timestamp: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    serverUptime: 7320000,
    jobWorkersActive: 5,
    queueSize: 8,
    cpuUsage: 42.3,
    memoryUsage: 61.5,
    apiLatency: 118,
    timestamp: new Date(),
  },
]

export const dummyRecentActivities: RecentActivity[] = [
  {
    id: "1",
    type: "sales_sync",
    repName: "Ahmed Ali",
    vanCode: "VAN-001",
    status: "success",
    timestamp: new Date(Date.now() - 10 * 60 * 1000),
    message: "Sales data synced successfully",
  },
  {
    id: "2",
    type: "delivery",
    repName: "Mohammed Hassan",
    vanCode: "VAN-002",
    status: "success",
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    message: "Delivery completed: 12 items to Shop-15",
  },
  {
    id: "3",
    type: "payment",
    repName: "Ahmed Ali",
    vanCode: "VAN-001",
    status: "success",
    timestamp: new Date(Date.now() - 20 * 60 * 1000),
    message: "Payment received: SAR 1,250.00",
  },
  {
    id: "4",
    type: "inventory_sync",
    repName: "Mohammed Hassan",
    vanCode: "VAN-002",
    status: "success",
    timestamp: new Date(Date.now() - 25 * 60 * 1000),
    message: "Inventory updated successfully",
  },
  {
    id: "5",
    type: "delivery",
    repName: "Khalid Ibrahim",
    vanCode: "VAN-003",
    status: "success",
    timestamp: new Date(Date.now() - 30 * 60 * 1000),
    message: "Delivery completed: 8 items to Shop-22",
  },
  {
    id: "6",
    type: "sales_sync",
    repName: "Khalid Ibrahim",
    vanCode: "VAN-003",
    status: "failed",
    timestamp: new Date(Date.now() - 45 * 60 * 1000),
    message: "Sync failed: Connection timeout",
  },
  {
    id: "7",
    type: "payment",
    repName: "Yusuf Saleh",
    vanCode: "VAN-005",
    status: "success",
    timestamp: new Date(Date.now() - 50 * 60 * 1000),
    message: "Payment received: SAR 890.50",
  },
  {
    id: "8",
    type: "payment_sync",
    repName: "Yusuf Saleh",
    vanCode: "VAN-005",
    status: "success",
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
    message: "Payment transactions synced",
  },
  {
    id: "9",
    type: "delivery",
    repName: "Omar Abdullah",
    vanCode: "VAN-004",
    status: "success",
    timestamp: new Date(Date.now() - 1.5 * 60 * 60 * 1000),
    message: "Delivery completed: 15 items to Shop-8",
  },
  {
    id: "10",
    type: "sales_sync",
    repName: "Ahmed Ali",
    vanCode: "VAN-001",
    status: "success",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    message: "Sales data synced successfully",
  },
]

export const dummySyncMetrics: SyncMetrics[] = Array.from({ length: 24 }, (_, i) => ({
  timestamp: new Date(Date.now() - (23 - i) * 60 * 60 * 1000),
  successRate: 85 + Math.random() * 10,
  attempts: Math.floor(20 + Math.random() * 30),
  errors: Math.floor(2 + Math.random() * 5),
}))

export const getKPIs = (): DashboardKPIs => {
  const totalVans = dummyVans.length
  const activeVans = dummyVans.filter((v) => v.status === "active").length
  const activeReps = dummyReps.filter((r) => r.status === "active").length
  const todayDeliveries = 45 // Mock data
  const failedSyncs = dummySyncLogs.filter((log) => log.status === "failed").length
  const successfulSyncs = dummySyncLogs.filter((log) => log.status === "success").length
  const syncSuccessRate = dummySyncLogs.length > 0
    ? Math.round((successfulSyncs / dummySyncLogs.length) * 100)
    : 0
  const lowStockVans = dummyVans.filter((v) => v.inventoryLoaded && (v.currentLoad || 0) < v.capacity * 0.2).length
  const totalQueueItems = dummyQueueItems.length

  return {
    totalVans,
    activeVans,
    activeReps,
    todayDeliveries,
    syncSuccessRate,
    failedSyncs,
    lowStockVans,
    totalQueueItems,
  }
}
